name: Release

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: false
        default: 'main'
      section:
        type: string
        required: false
        default: 'patch'
      version:
        type: string
        required: false
      release-command:
        type: string
        required: false
        default: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository -Pversion=%NEXT_VERSION%
      snapshot-command:
        type: string
        required: false
        default: ./gradlew publishToSonatype -Pversion=%NEXT_VERSION%

jobs:
  release:
    uses: coditory/workflows/.github/workflows/release.yml@v1
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}
      section: ${{ inputs.section }}
      version: ${{ inputs.version }}
      release-command: echo "Simulating %NEXT_VERSION% release publish to maven central..."
      snapshot-command: echo "Simulating %NEXT_VERSION% snapshot publish to maven central..."
